"""
PDF generation utilities.

Original: build_attendance_pdf (class attendance detail — unchanged)
New:
  build_student_analysis_pdf   — full student report with charts
  build_class_analysis_pdf     — full class report with charts
  build_teacher_analysis_pdf   — teacher activity report with charts
  build_teacher_comparison_pdf — all-teachers comparison report
  build_school_overview_pdf    — school-wide overview (superadmin)

Charts are rendered with matplotlib (non-interactive Agg backend) and
embedded as PNG images inside ReportLab flowables.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── colour palette ─────────────────────────────────────────────────────────────
C_PRESENT = "#27AE60"
C_ABSENT  = "#E74C3C"
C_LATE    = "#F39C12"
C_EXCUSED = "#2980B9"
C_HEADER  = "#1F4E78"
C_HEADER2 = "#2C3E50"
C_ALT_ROW = "#F8F9F9"
C_META    = "#4B5563"

MAX_DETAIL_ROWS = 1000


# ══════════════════════════════════════════════════════════════════════════════
# Shared helpers
# ══════════════════════════════════════════════════════════════════════════════

def _styles():
    s = getSampleStyleSheet()
    defs = [
        ("ReportTitle",  "Heading1", "Helvetica-Bold", 18, TA_CENTER, "#1F2937"),
        ("SchoolName",   "Heading2", "Helvetica-Bold", 16, TA_CENTER, "#0F172A"),
        ("SectionTitle", "Heading3", "Helvetica-Bold", 11, TA_LEFT,   "#111827"),
        ("Meta",         "Normal",   "Helvetica",       9, TA_LEFT,   C_META),
        ("MetaRight",    "Normal",   "Helvetica",       9, TA_RIGHT,  C_META),
        ("CellText",     "BodyText", "Helvetica",       8, TA_LEFT,   "#000000"),
        ("CellCenter",   "BodyText", "Helvetica",       8, TA_CENTER, "#000000"),
        ("SmallNote",    "Normal",   "Helvetica",       7, TA_LEFT,   C_META),
    ]
    for name, parent, font, size, align, hex_color in defs:
        s.add(ParagraphStyle(
            name=name, parent=s[parent],
            fontName=font, fontSize=size,
            alignment=align,
            textColor=colors.HexColor(hex_color),
            spaceAfter=2,
        ))
    return s


def _make_doc(buffer, title: str, use_landscape: bool = True):
    ps = landscape(A4) if use_landscape else A4
    return SimpleDocTemplate(
        buffer, pagesize=ps,
        leftMargin=12*mm, rightMargin=12*mm,
        topMargin=12*mm, bottomMargin=18*mm,
        title=title, author="NeptuneAMS Analytics",
    )


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(12*mm, 8*mm, "Generated by NeptuneAMS Analytics")
    w = doc.pagesize[0]
    canvas.drawRightString(w - 12*mm, 8*mm, f"Page {doc.page}")
    canvas.restoreState()


def _header_block(styles, school_name: str, report_title: str, meta_lines: list[str]):
    items = [
        Paragraph(school_name, styles["SchoolName"]),
        Paragraph(report_title, styles["ReportTitle"]),
    ]
    for line in meta_lines:
        items.append(Paragraph(line, styles["Meta"]))
    items.append(Spacer(1, 10))
    return items


def _summary_table(styles, cols: list[str], vals: list[str], total_width_mm: float = 252):
    n = len(cols)
    w = total_width_mm / n
    data = [cols, vals]
    t = Table(data, colWidths=[w*mm]*n)
    t.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), colors.HexColor(C_HEADER)),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME",     (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1,-1), 10),
        ("ALIGN",        (0, 0), (-1,-1), "CENTER"),
        ("VALIGN",       (0, 0), (-1,-1), "MIDDLE"),
        ("BACKGROUND",   (0, 1), (-1, 1), colors.HexColor("#EAF2F8")),
        ("BOX",          (0, 0), (-1,-1), 0.6, colors.HexColor("#AAB7B8")),
        ("INNERGRID",    (0, 0), (-1,-1), 0.4, colors.HexColor("#D5D8DC")),
        ("TOPPADDING",   (0, 0), (-1,-1), 8),
        ("BOTTOMPADDING",(0, 0), (-1,-1), 8),
    ]))
    return t


def _status_cell(status: str, styles):
    s = str(status).strip().lower()
    colour_map = {"present": "green", "absent": "red", "late": "orange", "excused": "blue"}
    colour = colour_map.get(s, "black")
    return Paragraph(f'<font color="{colour}"><b>{s.title()}</b></font>', styles["CellCenter"])


def _section(styles, title: str):
    return [Paragraph(title, styles["SectionTitle"]), Spacer(1, 4)]


def _signature_block(styles):
    data = [["Prepared By:", "", "Approved By:", ""], ["", "", "", ""]]
    t = Table(data, colWidths=[30*mm, 70*mm, 30*mm, 70*mm])
    t.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (-1,-1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1,-1), 9),
        ("LINEBELOW",   (1, 0), (1, 0), 0.5, colors.black),
        ("LINEBELOW",   (3, 0), (3, 0), 0.5, colors.black),
        ("TOPPADDING",  (0, 0), (-1,-1), 10),
    ]))
    return [Paragraph("Authorization", styles["SectionTitle"]), t]


def _apply_data_table_style(table: Table, alert: bool = False) -> None:
    header_bg = colors.HexColor(C_ABSENT if alert else C_HEADER2)
    table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 8),
        ("FONTSIZE",      (0, 1), (-1,-1), 8),
        ("ALIGN",         (0, 0), (-1,-1), "CENTER"),
        ("VALIGN",        (0, 0), (-1,-1), "MIDDLE"),
        ("GRID",          (0, 0), (-1,-1), 0.3, colors.HexColor("#D0D7DE")),
        ("ROWBACKGROUNDS",(0, 1), (-1,-1), [colors.white, colors.HexColor(C_ALT_ROW)]),
        ("TOPPADDING",    (0, 0), (-1,-1), 5),
        ("BOTTOMPADDING", (0, 0), (-1,-1), 5),
    ]))


# ══════════════════════════════════════════════════════════════════════════════
# Chart helpers
# ══════════════════════════════════════════════════════════════════════════════

def _fig_to_image(fig, width_mm: float, height_mm: float) -> Image:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return Image(buf, width=width_mm*mm, height=height_mm*mm)


def _bar_chart(labels, values, title, ylabel="Count",
               color=C_PRESENT, width_mm=240, height_mm=65) -> Image:
    fig, ax = plt.subplots(figsize=(width_mm/25.4, height_mm/25.4))
    x = np.arange(len(labels))
    ax.bar(x, values, color=color, edgecolor="white", linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=7)
    ax.set_ylabel(ylabel, fontsize=8)
    ax.set_title(title, fontsize=9, fontweight="bold")
    ax.yaxis.set_major_locator(mticker.MaxNLocator(integer=True))
    ax.grid(axis="y", linestyle="--", alpha=0.4)
    fig.tight_layout()
    return _fig_to_image(fig, width_mm, height_mm)


def _line_chart(labels, series: dict[str, list[float]], title,
                ylabel="Rate (%)", width_mm=240, height_mm=65) -> Image:
    palette = [C_PRESENT, C_ABSENT, C_LATE, C_EXCUSED, "#8E44AD", "#16A085"]
    fig, ax = plt.subplots(figsize=(width_mm/25.4, height_mm/25.4))
    x = np.arange(len(labels))
    for idx, (name, vals) in enumerate(series.items()):
        ax.plot(x, vals, marker="o", markersize=3, linewidth=1.2,
                label=name, color=palette[idx % len(palette)])
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=7)
    ax.set_ylabel(ylabel, fontsize=8)
    ax.set_title(title, fontsize=9, fontweight="bold")
    ax.legend(fontsize=7, loc="best")
    ax.grid(linestyle="--", alpha=0.4)
    fig.tight_layout()
    return _fig_to_image(fig, width_mm, height_mm)


def _stacked_bar(labels, stacks: dict[str, list[float]],
                 stack_colors: dict[str, str], title,
                 ylabel="Records", width_mm=240, height_mm=65) -> Image:
    fig, ax = plt.subplots(figsize=(width_mm/25.4, height_mm/25.4))
    x = np.arange(len(labels))
    bottom = np.zeros(len(labels))
    for name, vals in stacks.items():
        v = np.array(vals, dtype=float)
        ax.bar(x, v, bottom=bottom, label=name,
               color=stack_colors.get(name, "#999"), edgecolor="white", linewidth=0.4)
        bottom += v
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=7)
    ax.set_ylabel(ylabel, fontsize=8)
    ax.set_title(title, fontsize=9, fontweight="bold")
    ax.legend(fontsize=7, loc="upper right")
    ax.grid(axis="y", linestyle="--", alpha=0.4)
    fig.tight_layout()
    return _fig_to_image(fig, width_mm, height_mm)


def _pie_chart(labels, sizes, colors_list, title,
               width_mm=90, height_mm=70) -> Image:
    fig, ax = plt.subplots(figsize=(width_mm/25.4, height_mm/25.4))
    non_zero = [(l, s, c) for l, s, c in zip(labels, sizes, colors_list) if s > 0]
    if non_zero:
        ls, ss, cs = zip(*non_zero)
        ax.pie(ss, labels=ls, colors=cs, autopct="%1.1f%%",
               startangle=140, textprops={"fontsize": 7})
    ax.set_title(title, fontsize=9, fontweight="bold")
    fig.tight_layout()
    return _fig_to_image(fig, width_mm, height_mm)


def _horizontal_bar(labels, values, title, xlabel="Rate (%)",
                    width_mm=240, height_mm=80) -> Image:
    fig, ax = plt.subplots(figsize=(width_mm/25.4, height_mm/25.4))
    y = np.arange(len(labels))
    clrs = [C_ABSENT if v < 75 else C_LATE if v < 90 else C_PRESENT for v in values]
    ax.barh(y, values, color=clrs, edgecolor="white", linewidth=0.4)
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=7)
    ax.set_xlabel(xlabel, fontsize=8)
    ax.set_xlim(0, 105)
    ax.axvline(75, color=C_ABSENT, linewidth=0.8, linestyle="--", label="75% threshold")
    ax.axvline(90, color=C_LATE,   linewidth=0.8, linestyle="--", label="90% threshold")
    ax.legend(fontsize=7)
    ax.set_title(title, fontsize=9, fontweight="bold")
    ax.grid(axis="x", linestyle="--", alpha=0.4)
    fig.tight_layout()
    return _fig_to_image(fig, width_mm, height_mm)


# ══════════════════════════════════════════════════════════════════════════════
# ORIGINAL — Class attendance detail PDF (interface unchanged)
# ══════════════════════════════════════════════════════════════════════════════

def build_attendance_pdf(
    *,
    school_name: str,
    class_name: str,
    start_date: str,
    end_date: str,
    period: str | None,
    generated_by: str,
    rows: list[tuple],
) -> bytes:
    """rows: (session_date, period, student_id, student_name, status, note)"""
    summary = _build_raw_summary(rows)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    buffer = io.BytesIO()
    doc = _make_doc(buffer, "Attendance Report")
    st = _styles()
    story: list = []
    story += _header_block(st, school_name, "Attendance Report", [
        f"<b>Class:</b> {class_name} &nbsp;&nbsp;&nbsp; "
        f"<b>Period:</b> {period or 'All'} &nbsp;&nbsp;&nbsp; "
        f"<b>Date Range:</b> {start_date} to {end_date}",
        f"<b>Generated By:</b> {generated_by} &nbsp;&nbsp;&nbsp; "
        f"<b>Generated At:</b> {generated_at}",
    ])
    story += [
        *_section(st, "Summary"),
        _summary_table(st,
            ["Total Records", "Present", "Absent", "Late", "Excused", "Attendance Rate"],
            [str(summary["total"]), str(summary["present"]), str(summary["absent"]),
             str(summary["late"]), str(summary["excused"]), summary["rate"]],
        ),
        Spacer(1, 14),
    ]
    story += _build_detail_section(st, rows)
    story += _signature_block(st)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


def _build_raw_summary(rows: list[tuple]) -> dict:
    total   = len(rows)
    present = sum(1 for r in rows if str(r[4]).strip().lower() == "present")
    absent  = sum(1 for r in rows if str(r[4]).strip().lower() == "absent")
    late    = sum(1 for r in rows if str(r[4]).strip().lower() == "late")
    excused = sum(1 for r in rows if str(r[4]).strip().lower() == "excused")
    rate    = (present / total * 100) if total else 0
    return {"total": total, "present": present, "absent": absent,
            "late": late, "excused": excused, "rate": f"{rate:.1f}%"}


def _build_detail_section(styles, rows: list[tuple]):
    data = [["Date", "Period", "Student ID", "Student Name", "Status", "Note"]]
    for session_date, per, sid, name, stat, note in rows[:MAX_DETAIL_ROWS]:
        data.append([
            Paragraph(session_date.isoformat(), styles["CellCenter"]),
            Paragraph(str(per), styles["CellCenter"]),
            Paragraph(str(sid), styles["CellCenter"]),
            Paragraph(str(name), styles["CellText"]),
            _status_cell(str(stat), styles),
            Paragraph((note or "")[:120], styles["CellText"]),
        ])
    if len(rows) > MAX_DETAIL_ROWS:
        data.append([
            Paragraph(f"(truncated — {len(rows)} total rows)", styles["CellText"])
        ] + [""] * 5)
    if len(data) == 1:
        data.append([Paragraph("No attendance records found", styles["CellCenter"])] + [""] * 5)
    t = Table(data, repeatRows=1,
              colWidths=[28*mm, 22*mm, 28*mm, 55*mm, 24*mm, 95*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), colors.HexColor(C_HEADER2)),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 9),
        ("FONTSIZE",      (0, 1), (-1,-1), 8),
        ("ALIGN",         (0, 0), (2, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1,-1), "TOP"),
        ("GRID",          (0, 0), (-1,-1), 0.3, colors.HexColor("#D0D7DE")),
        ("ROWBACKGROUNDS",(0, 1), (-1,-1), [colors.white, colors.HexColor(C_ALT_ROW)]),
        ("TOPPADDING",    (0, 0), (-1,-1), 5),
        ("BOTTOMPADDING", (0, 0), (-1,-1), 5),
    ]))
    return [*_section(styles, "Attendance Details"), t, Spacer(1, 18)]


# ══════════════════════════════════════════════════════════════════════════════
# NEW — Student analysis PDF
# ══════════════════════════════════════════════════════════════════════════════

def build_student_analysis_pdf(
    *,
    school_name: str,
    student_name: str,
    student_id: str,
    generated_by: str,
    data: dict[str, Any],
) -> bytes:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    dr = data["date_range"]
    ov = data["overall"]
    buffer = io.BytesIO()
    doc = _make_doc(buffer, f"Student Analysis — {student_name}")
    st = _styles()
    story: list = []

    story += _header_block(st, school_name, "Student Attendance Analysis", [
        f"<b>Student:</b> {student_name} &nbsp;&nbsp;&nbsp; <b>ID:</b> {student_id}",
        f"<b>Date Range:</b> {dr['start']} to {dr['end']} &nbsp;&nbsp;&nbsp; "
        f"<b>Generated By:</b> {generated_by} &nbsp;&nbsp;&nbsp; <b>At:</b> {generated_at}",
    ])

    story += [
        *_section(st, "Overall Summary"),
        _summary_table(st,
            ["Total Sessions", "Present", "Absent", "Late", "Excused", "Attendance Rate"],
            [str(ov["total"]), str(ov["present"]), str(ov["absent"]),
             str(ov["late"]),  str(ov["excused"]), f"{ov['rate']}%"],
        ),
        Spacer(1, 12),
    ]

    # pie + monthly line side by side
    pie = _pie_chart(
        ["Present", "Absent", "Late", "Excused"],
        [ov["present"], ov["absent"], ov["late"], ov["excused"]],
        [C_PRESENT, C_ABSENT, C_LATE, C_EXCUSED],
        "Status Distribution", width_mm=90, height_mm=70,
    )
    if data["monthly_trend"]:
        m_labels = [r["label"] for r in data["monthly_trend"]]
        line_img = _line_chart(m_labels,
            {"Attendance Rate": [r["rate"] for r in data["monthly_trend"]]},
            "Monthly Attendance Rate (%)", width_mm=148, height_mm=70)
    else:
        line_img = Spacer(1, 1)

    sbs = Table([[pie, line_img]], colWidths=[95*mm, 153*mm])
    sbs.setStyle(TableStyle([("VALIGN", (0,0), (-1,-1), "TOP")]))
    story += [*_section(st, "Charts"), sbs, Spacer(1, 10)]

    # weekly stacked bar
    if data["weekly_trend"]:
        w_labels = [r["label"] for r in data["weekly_trend"]]
        story += [
            _stacked_bar(w_labels,
                {"Present": [r["present"] for r in data["weekly_trend"]],
                 "Late":    [r["late"]    for r in data["weekly_trend"]],
                 "Excused": [r["excused"] for r in data["weekly_trend"]],
                 "Absent":  [r["absent"]  for r in data["weekly_trend"]]},
                {"Present": C_PRESENT, "Late": C_LATE, "Excused": C_EXCUSED, "Absent": C_ABSENT},
                "Weekly Attendance Breakdown",
            ),
            Spacer(1, 10),
        ]

    # per-period table
    if data["by_period"]:
        story += _section(st, "Per-Period Breakdown")
        h = ["Period", "Total", "Present", "Absent", "Late", "Excused", "Rate"]
        pd_data = [h] + [
            [r["period"], r["total"], r["present"], r["absent"],
             r["late"], r["excused"], f"{r['rate']}%"]
            for r in data["by_period"]
        ]
        pt = Table(pd_data, colWidths=[35*mm, 25*mm, 25*mm, 25*mm, 25*mm, 25*mm, 25*mm])
        _apply_data_table_style(pt)
        story += [pt, Spacer(1, 10)]

    # absence streaks
    story += _section(st, "Worst Absence Streaks (consecutive absent days ≥ 2)")
    if data["absence_streaks"]:
        s_data = [["Start Date", "End Date", "Consecutive Days"]] + [
            [s["start"], s["end"], str(s["days"])] for s in data["absence_streaks"]
        ]
        s_tbl = Table(s_data, colWidths=[60*mm, 60*mm, 60*mm])
        _apply_data_table_style(s_tbl, alert=True)
        story += [s_tbl, Spacer(1, 10)]
    else:
        story += [Paragraph("No consecutive absence streaks detected.", st["Meta"]),
                  Spacer(1, 10)]

    # daily log
    story += [PageBreak(), *_section(st, "Full Daily Log")]
    daily = data.get("daily", [])
    d_data = [["Date", "Period", "Status", "Note"]]
    for d in daily[:MAX_DETAIL_ROWS]:
        d_data.append([
            Paragraph(d["date"],   st["CellCenter"]),
            Paragraph(d["period"], st["CellCenter"]),
            _status_cell(d["status"], st),
            Paragraph((d.get("note") or "")[:120], st["CellText"]),
        ])
    if len(daily) == 0:
        d_data.append([Paragraph("No records", st["CellCenter"]), "", "", ""])
    d_tbl = Table(d_data, repeatRows=1, colWidths=[35*mm, 30*mm, 30*mm, 152*mm])
    _apply_data_table_style(d_tbl)
    story += [d_tbl, Spacer(1, 18)]

    story += _signature_block(st)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


# ══════════════════════════════════════════════════════════════════════════════
# NEW — Class analysis PDF
# ══════════════════════════════════════════════════════════════════════════════

def build_class_analysis_pdf(
    *,
    school_name: str,
    class_name: str,
    generated_by: str,
    data: dict[str, Any],
) -> bytes:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    dr = data["date_range"]
    ov = data["overall"]
    buffer = io.BytesIO()
    doc = _make_doc(buffer, f"Class Analysis — {class_name}")
    st = _styles()
    story: list = []

    story += _header_block(st, school_name, "Class Attendance Analysis", [
        f"<b>Class:</b> {class_name} &nbsp;&nbsp;&nbsp; "
        f"<b>Students:</b> {data['student_count']} &nbsp;&nbsp;&nbsp; "
        f"<b>Date Range:</b> {dr['start']} to {dr['end']}",
        f"<b>Generated By:</b> {generated_by} &nbsp;&nbsp;&nbsp; <b>At:</b> {generated_at}",
    ])

    story += [
        *_section(st, "Overall Summary"),
        _summary_table(st,
            ["Total Records", "Present", "Absent", "Late", "Excused", "Attendance Rate"],
            [str(ov["total"]), str(ov["present"]), str(ov["absent"]),
             str(ov["late"]),  str(ov["excused"]), f"{ov['rate']}%"],
        ),
        Spacer(1, 12),
    ]

    pie = _pie_chart(
        ["Present", "Absent", "Late", "Excused"],
        [ov["present"], ov["absent"], ov["late"], ov["excused"]],
        [C_PRESENT, C_ABSENT, C_LATE, C_EXCUSED],
        "Status Distribution", width_mm=90, height_mm=70,
    )
    if data["monthly_trend"]:
        m_labels = [r["label"] for r in data["monthly_trend"]]
        line_img = _line_chart(m_labels,
            {"Attendance Rate": [r["rate"] for r in data["monthly_trend"]]},
            "Monthly Attendance Rate (%)", width_mm=148, height_mm=70)
    else:
        line_img = Spacer(1, 1)
    sbs = Table([[pie, line_img]], colWidths=[95*mm, 153*mm])
    sbs.setStyle(TableStyle([("VALIGN", (0,0), (-1,-1), "TOP")]))
    story += [*_section(st, "Charts"), sbs, Spacer(1, 10)]

    if data["weekly_trend"]:
        w_labels = [r["label"] for r in data["weekly_trend"]]
        story += [
            _stacked_bar(w_labels,
                {"Present": [r["present"] for r in data["weekly_trend"]],
                 "Late":    [r["late"]    for r in data["weekly_trend"]],
                 "Excused": [r["excused"] for r in data["weekly_trend"]],
                 "Absent":  [r["absent"]  for r in data["weekly_trend"]]},
                {"Present": C_PRESENT, "Late": C_LATE, "Excused": C_EXCUSED, "Absent": C_ABSENT},
                "Weekly Attendance Breakdown",
            ),
            Spacer(1, 8),
        ]

    if data["daily_trend"]:
        d_labels = [r["date"] for r in data["daily_trend"]]
        story += [
            _line_chart(d_labels,
                {"Daily Rate": [r["rate"] for r in data["daily_trend"]]},
                "Daily Attendance Rate (%)",
            ),
            Spacer(1, 8),
        ]

    if data["by_period"]:
        story += _section(st, "Per-Period Breakdown")
        h = ["Period", "Total", "Present", "Absent", "Late", "Excused", "Rate"]
        pd_data = [h] + [
            [r["period"], r["total"], r["present"], r["absent"],
             r["late"], r["excused"], f"{r['rate']}%"]
            for r in data["by_period"]
        ]
        pt = Table(pd_data, colWidths=[35*mm, 25*mm, 25*mm, 25*mm, 25*mm, 25*mm, 25*mm])
        _apply_data_table_style(pt)
        story += [pt, Spacer(1, 10)]

    summaries = data["student_summaries"]
    if summaries:
        s_labels = [s["student_name"] for s in summaries]
        s_rates  = [s["rate"]         for s in summaries]
        bar_h = max(65, len(s_labels) * 6)
        story += [
            PageBreak(),
            *_section(st, "Student Attendance Rates"),
            _horizontal_bar(s_labels, s_rates,
                            "Attendance Rate per Student (%)",
                            width_mm=240, height_mm=min(bar_h, 160)),
            Spacer(1, 8),
            *_section(st, "Student Summary Table"),
        ]
        h2 = ["Student Name", "ID", "Total", "Present", "Absent", "Late", "Excused", "Rate"]
        s_data = [h2] + [
            [s["student_name"], s["student_id"], s["total"],
             s["present"], s["absent"], s["late"], s["excused"], f"{s['rate']}%"]
            for s in summaries
        ]
        s_tbl = Table(s_data, repeatRows=1,
                      colWidths=[55*mm, 30*mm, 20*mm, 22*mm, 22*mm, 20*mm, 22*mm, 22*mm])
        _apply_data_table_style(s_tbl)
        story += [s_tbl, Spacer(1, 10)]

    # at-risk
    story += _section(st, "At-Risk Students (Rate < 75%)")
    at_risk = data["at_risk_students"]
    if at_risk:
        ar_data = [["Student Name", "ID", "Rate", "Absent", "Total"]] + [
            [s["student_name"], s["student_id"], f"{s['rate']}%", s["absent"], s["total"]]
            for s in at_risk
        ]
        ar_tbl = Table(ar_data, colWidths=[70*mm, 40*mm, 30*mm, 40*mm, 30*mm])
        _apply_data_table_style(ar_tbl, alert=True)
        story += [ar_tbl, Spacer(1, 10)]
    else:
        story += [Paragraph("No at-risk students in this period.", st["Meta"]), Spacer(1, 6)]

    # perfect attendance
    story += _section(st, "Perfect Attendance (100%)")
    perfect = data["perfect_attendance"]
    if perfect:
        pf_data = [["Student Name", "ID", "Total Sessions"]] + [
            [s["student_name"], s["student_id"], s["total"]] for s in perfect
        ]
        pf_tbl = Table(pf_data, colWidths=[100*mm, 60*mm, 60*mm])
        _apply_data_table_style(pf_tbl)
        story += [pf_tbl, Spacer(1, 10)]
    else:
        story += [Paragraph("No students with perfect attendance in this period.", st["Meta"]),
                  Spacer(1, 6)]

    story += _signature_block(st)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


# ══════════════════════════════════════════════════════════════════════════════
# NEW — Teacher activity PDF (single teacher)
# ══════════════════════════════════════════════════════════════════════════════

def build_teacher_analysis_pdf(
    *,
    school_name: str,
    teacher_name: str,
    generated_by: str,
    data: dict[str, Any],
) -> bytes:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    dr = data["date_range"]
    ov = data["overall"]
    buffer = io.BytesIO()
    doc = _make_doc(buffer, f"Teacher Activity — {teacher_name}")
    st = _styles()
    story: list = []

    story += _header_block(st, school_name, "Teacher Activity Report", [
        f"<b>Teacher:</b> {teacher_name}",
        f"<b>Date Range:</b> {dr['start']} to {dr['end']} &nbsp;&nbsp;&nbsp; "
        f"<b>Generated By:</b> {generated_by} &nbsp;&nbsp;&nbsp; <b>At:</b> {generated_at}",
    ])

    story += [
        *_section(st, "Overall Activity Summary"),
        _summary_table(st,
            ["Records Marked", "Active Days", "Days in Range", "Activity Rate",
             "Notes Used", "Notes Usage Rate"],
            [str(ov["total_marked"]), str(ov["active_days"]),
             str(ov["days_in_range"]), f"{ov['activity_rate']}%",
             str(ov["with_notes"]),   f"{ov['notes_usage_rate']}%"],
        ),
        Spacer(1, 8),
        _summary_table(st,
            ["Present Marked", "Absent Marked", "Late Marked", "Excused Marked"],
            [str(ov["present"]), str(ov["absent"]), str(ov["late"]), str(ov["excused"])],
            total_width_mm=168,
        ),
        Spacer(1, 12),
    ]

    pie = _pie_chart(
        ["Present", "Absent", "Late", "Excused"],
        [ov["present"], ov["absent"], ov["late"], ov["excused"]],
        [C_PRESENT, C_ABSENT, C_LATE, C_EXCUSED],
        "Status Distribution", width_mm=90, height_mm=70,
    )
    if data["monthly_trend"]:
        m_labels = [r["label"] for r in data["monthly_trend"]]
        bar_img = _bar_chart(m_labels,
            [r["total_marked"] for r in data["monthly_trend"]],
            "Monthly Records Marked", ylabel="Records",
            color=C_HEADER, width_mm=148, height_mm=70)
    else:
        bar_img = Spacer(1, 1)
    sbs = Table([[pie, bar_img]], colWidths=[95*mm, 153*mm])
    sbs.setStyle(TableStyle([("VALIGN", (0,0), (-1,-1), "TOP")]))
    story += [*_section(st, "Charts"), sbs, Spacer(1, 10)]

    if data["weekly_trend"]:
        w_labels = [r["label"] for r in data["weekly_trend"]]
        story += [
            _stacked_bar(w_labels,
                {"Present": [r["present"] for r in data["weekly_trend"]],
                 "Absent":  [r["absent"]  for r in data["weekly_trend"]]},
                {"Present": C_PRESENT, "Absent": C_ABSENT},
                "Weekly Records Marked",
            ),
            Spacer(1, 8),
        ]

    if data["daily_volume"]:
        d_labels = [r["date"] for r in data["daily_volume"]]
        story += [
            _line_chart(d_labels,
                {"Records Marked": [r["total_marked"] for r in data["daily_volume"]]},
                "Daily Marking Volume", ylabel="Records",
            ),
            Spacer(1, 8),
        ]

    if data["per_class"]:
        story += _section(st, "Per-Class Breakdown")
        h = ["Class", "Total Marked", "Present", "Absent", "Late", "Excused", "Active Days"]
        pc_data = [h] + [
            [r["class_name"], r["total"], r["present"], r["absent"],
             r["late"], r["excused"], r["active_days"]]
            for r in data["per_class"]
        ]
        pc_tbl = Table(pc_data, repeatRows=1,
                       colWidths=[55*mm, 30*mm, 25*mm, 25*mm, 25*mm, 25*mm, 30*mm])
        _apply_data_table_style(pc_tbl)
        story += [pc_tbl, Spacer(1, 10)]

    if data["by_period"]:
        story += _section(st, "Per-Period Breakdown")
        h2 = ["Period", "Total Marked", "Active Days"]
        pp_data = [h2] + [
            [r["period"], r["total_marked"], r["days_active"]]
            for r in data["by_period"]
        ]
        pp_tbl = Table(pp_data, colWidths=[60*mm, 60*mm, 60*mm])
        _apply_data_table_style(pp_tbl)
        story += [pp_tbl, Spacer(1, 10)]

    story += _signature_block(st)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


# ══════════════════════════════════════════════════════════════════════════════
# NEW — All-teachers comparison PDF
# ══════════════════════════════════════════════════════════════════════════════

def build_teacher_comparison_pdf(
    *,
    school_name: str,
    generated_by: str,
    start: str,
    end: str,
    teachers: list[dict[str, Any]],
) -> bytes:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    buffer = io.BytesIO()
    doc = _make_doc(buffer, "Teacher Comparison Report")
    st = _styles()
    story: list = []

    story += _header_block(st, school_name, "Teacher Activity Comparison", [
        f"<b>Date Range:</b> {start} to {end}",
        f"<b>Generated By:</b> {generated_by} &nbsp;&nbsp;&nbsp; <b>At:</b> {generated_at}",
    ])

    story += _section(st, f"All Teachers Summary ({len(teachers)} teachers)")
    h = ["Teacher", "Records Marked", "Active Days", "Activity Rate",
         "Classes Covered", "Notes Usage"]
    t_data = [h] + [
        [t["teacher_name"], t["total_marked"], t["active_days"],
         f"{t['activity_rate']}%", t["classes_covered"],
         f"{t['notes_usage_rate']}%"]
        for t in teachers
    ]
    t_tbl = Table(t_data, repeatRows=1,
                  colWidths=[65*mm, 35*mm, 30*mm, 35*mm, 35*mm, 35*mm])
    _apply_data_table_style(t_tbl)
    story += [t_tbl, Spacer(1, 14)]

    if teachers:
        names  = [t["teacher_name"]      for t in teachers]
        rates  = [t["activity_rate"]     for t in teachers]
        totals = [t["total_marked"]      for t in teachers]
        notes  = [t["notes_usage_rate"]  for t in teachers]
        bar_h  = max(65, len(names) * 7)

        story += [
            *_section(st, "Activity Rate per Teacher (%)"),
            _horizontal_bar(names, rates, "Activity Rate (%)",
                            width_mm=240, height_mm=min(bar_h, 160)),
            Spacer(1, 10),
            *_section(st, "Total Records Marked per Teacher"),
            _bar_chart(names, totals, "Records Marked",
                       ylabel="Records", color=C_HEADER, width_mm=240, height_mm=65),
            Spacer(1, 10),
            *_section(st, "Notes Usage Rate per Teacher (%)"),
            _bar_chart(names, notes, "Notes Usage Rate (%)",
                       ylabel="Rate (%)", color=C_EXCUSED, width_mm=240, height_mm=65),
            Spacer(1, 10),
        ]

    story += _signature_block(st)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


# ══════════════════════════════════════════════════════════════════════════════
# NEW — School overview PDF (superadmin)
# ══════════════════════════════════════════════════════════════════════════════

def build_school_overview_pdf(
    *,
    school_name: str,
    generated_by: str,
    data: dict[str, Any],
) -> bytes:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    dr = data["date_range"]
    ov = data["overall"]
    buffer = io.BytesIO()
    doc = _make_doc(buffer, f"School Overview — {school_name}")
    st = _styles()
    story: list = []

    story += _header_block(st, school_name, "School Attendance Overview", [
        f"<b>Date Range:</b> {dr['start']} to {dr['end']}",
        f"<b>Generated By:</b> {generated_by} &nbsp;&nbsp;&nbsp; <b>At:</b> {generated_at}",
    ])

    story += [
        *_section(st, "School-Wide Summary"),
        _summary_table(st,
            ["Total Records", "Present", "Absent", "Late", "Excused", "Overall Rate"],
            [str(ov["total"]), str(ov["present"]), str(ov["absent"]),
             str(ov["late"]),  str(ov["excused"]), f"{ov['rate']}%"],
        ),
        Spacer(1, 12),
    ]

    if data["monthly_trend"]:
        m_labels = [r["label"] for r in data["monthly_trend"]]
        story += [
            *_section(st, "Monthly Attendance Rate Trend"),
            _line_chart(m_labels,
                {"School Rate": [r["rate"] for r in data["monthly_trend"]]},
                "Monthly Attendance Rate (%)",
            ),
            Spacer(1, 10),
        ]

    per_class = data["per_class"]
    if per_class:
        c_names = [c["class_name"] for c in per_class]
        c_rates = [c["rate"]       for c in per_class]
        bar_h   = max(65, len(c_names) * 7)
        story += [
            *_section(st, "Attendance Rate by Class"),
            _horizontal_bar(c_names, c_rates, "Attendance Rate per Class (%)",
                            width_mm=240, height_mm=min(bar_h, 160)),
            Spacer(1, 10),
            *_section(st, "Per-Class Detail Table"),
        ]
        h = ["Class", "Total", "Present", "Absent", "Late", "Excused", "Rate"]
        c_data = [h] + [
            [c["class_name"], c["total"], c["present"], c["absent"],
             c["late"], c["excused"], f"{c['rate']}%"]
            for c in per_class
        ]
        c_tbl = Table(c_data, repeatRows=1,
                      colWidths=[55*mm, 25*mm, 25*mm, 25*mm, 25*mm, 25*mm, 25*mm])
        _apply_data_table_style(c_tbl)
        story += [c_tbl, Spacer(1, 10)]

    story += _signature_block(st)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()
